version: '3.8'
services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./streamlit:/app/streamlit
    environment:
      - PYTHONPATH=/app